### PR TITLE
Feature/refactor to property injection

### PR DESCRIPTION
**Pull request by edward-mtsh**
Updated Home Interactor and Presenter to Property Injection

### CODE REVIEW

**Comment by pjwelcome** [comment]
Whats is the point or the benefits of this approach, and why did you change this ? @edward-mtsh

**Comment by edward-mtsh** [comment]
The constructor and property injection serves the same purpose. In our approach with constructor injection the was too much circulation of dependencies. So the property injection simplifies that for us. Easier to maintain and understand our objects dependencies.

**Comment by pjwelcome** [comment]
I dont really agree with what you are saying but if thats the approach you guys want to take thats cool. As long as it doesnt affect the tests

**Comment by pjwelcome** [comment]
Also everything now needs to be optional when it didnt need to before. We should try and move away from trying to make things optional so that our code is more concise.
Ill merge your PR's for now but I think you guys should rethink this.

**Review by pjwelcome — APPROVED** [review]

**Pull request merged**
