### PR TITLE
Added container injection for contact us

### PR DESCRIPTION
**Pull request by edward-mtsh**
Added container injection for contact
Updated title on navigation bar

### CODE REVIEW

**Review by pjwelcome — APPROVED** [review]
@edward-mtsh Please can you just put pictures for these screens on the PR so I can see what this looks like.

**Comment by edward-mtsh** [comment]
screen shot 2018-05-22 at 11 43 12

**Comment by edward-mtsh** [comment]
screen shot 2018-05-22 at 11 43 41

**Comment by edward-mtsh** [comment]
screen shot 2018-05-22 at 11 43 55

**Comment by edward-mtsh** [comment]
The fix for the home screen is on the searchBar branch PR

**Pull request merged**
